//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.29 at 03:33:15 下午 CST 
//


package org.solmix.api.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tvalidator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tvalidator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="list" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dependentFields" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valueMap" type="{http://www.solmix.org/xmlns/datasource/v1.0.1}TvalueMap"/>
 *         &lt;element name="serverCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="service" type="{http://www.solmix.org/xmlns/datasource/v1.0.1}Tservice"/>
 *       &lt;/choice>
 *       &lt;attribute name="clientOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="type" use="required" type="{http://www.solmix.org/xmlns/datasource/v1.0.1}Evalidator" />
 *       &lt;attribute name="stopIfFalse" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serverOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="validateOnChange " type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="exclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="mask" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transformTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="expression" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="otherField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="substring" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tvalidator", propOrder = {
    "list",
    "dependentFields",
    "valueMap",
    "serverCondition",
    "service"
})
public class Tvalidator {

    protected List<String> list;
    protected String dependentFields;
    protected TvalueMap valueMap;
    protected String serverCondition;
    protected Tservice service;
    @XmlAttribute
    protected Boolean clientOnly;
    @XmlAttribute(required = true)
    protected Evalidator type;
    @XmlAttribute
    protected Boolean stopIfFalse;
    @XmlAttribute
    protected String errorMessage;
    @XmlAttribute(namespace = "http://www.solmix.org/xmlns/datasource/v1.0.1")
    protected Boolean serverOnly;
    @XmlAttribute(name = "validateOnChange ", namespace = "http://www.solmix.org/xmlns/datasource/v1.0.1")
    protected Boolean validateOnChange0020;
    @XmlAttribute
    protected Double max;
    @XmlAttribute
    protected Double min;
    @XmlAttribute
    protected Boolean exclusive;
    @XmlAttribute
    protected String mask;
    @XmlAttribute
    protected String transformTo;
    @XmlAttribute
    protected Double precision;
    @XmlAttribute
    protected String expression;
    @XmlAttribute
    protected String otherField;
    @XmlAttribute
    protected String substring;
    @XmlAttribute
    protected String operator;
    @XmlAttribute(namespace = "http://www.solmix.org/xmlns/datasource/v1.0.1")
    protected Long count;

    /**
     * Gets the value of the list property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the list property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getList() {
        if (list == null) {
            list = new ArrayList<String>();
        }
        return this.list;
    }

    /**
     * Gets the value of the dependentFields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependentFields() {
        return dependentFields;
    }

    /**
     * Sets the value of the dependentFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependentFields(String value) {
        this.dependentFields = value;
    }

    /**
     * Gets the value of the valueMap property.
     * 
     * @return
     *     possible object is
     *     {@link TvalueMap }
     *     
     */
    public TvalueMap getValueMap() {
        return valueMap;
    }

    /**
     * Sets the value of the valueMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link TvalueMap }
     *     
     */
    public void setValueMap(TvalueMap value) {
        this.valueMap = value;
    }

    /**
     * Gets the value of the serverCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerCondition() {
        return serverCondition;
    }

    /**
     * Sets the value of the serverCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerCondition(String value) {
        this.serverCondition = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link Tservice }
     *     
     */
    public Tservice getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tservice }
     *     
     */
    public void setService(Tservice value) {
        this.service = value;
    }

    /**
     * Gets the value of the clientOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isClientOnly() {
        if (clientOnly == null) {
            return false;
        } else {
            return clientOnly;
        }
    }

    /**
     * Sets the value of the clientOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClientOnly(Boolean value) {
        this.clientOnly = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Evalidator }
     *     
     */
    public Evalidator getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Evalidator }
     *     
     */
    public void setType(Evalidator value) {
        this.type = value;
    }

    /**
     * Gets the value of the stopIfFalse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStopIfFalse() {
        if (stopIfFalse == null) {
            return false;
        } else {
            return stopIfFalse;
        }
    }

    /**
     * Sets the value of the stopIfFalse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStopIfFalse(Boolean value) {
        this.stopIfFalse = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the serverOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServerOnly() {
        return serverOnly;
    }

    /**
     * Sets the value of the serverOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServerOnly(Boolean value) {
        this.serverOnly = value;
    }

    /**
     * Gets the value of the validateOnChange0020 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValidateOnChange_0020() {
        return validateOnChange0020;
    }

    /**
     * Sets the value of the validateOnChange0020 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValidateOnChange_0020(Boolean value) {
        this.validateOnChange0020 = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMax(Double value) {
        this.max = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMin(Double value) {
        this.min = value;
    }

    /**
     * Gets the value of the exclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExclusive() {
        if (exclusive == null) {
            return false;
        } else {
            return exclusive;
        }
    }

    /**
     * Sets the value of the exclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExclusive(Boolean value) {
        this.exclusive = value;
    }

    /**
     * Gets the value of the mask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMask() {
        return mask;
    }

    /**
     * Sets the value of the mask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMask(String value) {
        this.mask = value;
    }

    /**
     * Gets the value of the transformTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformTo() {
        return transformTo;
    }

    /**
     * Sets the value of the transformTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformTo(String value) {
        this.transformTo = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPrecision(Double value) {
        this.precision = value;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpression(String value) {
        this.expression = value;
    }

    /**
     * Gets the value of the otherField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherField() {
        return otherField;
    }

    /**
     * Sets the value of the otherField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherField(String value) {
        this.otherField = value;
    }

    /**
     * Gets the value of the substring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstring() {
        return substring;
    }

    /**
     * Sets the value of the substring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstring(String value) {
        this.substring = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCount(Long value) {
        this.count = value;
    }

}
