//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 04:57:48 下午 CST 
//


package com.solmix.api.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EexportAs.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EexportAs">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="csv"/>
 *     &lt;enumeration value="json"/>
 *     &lt;enumeration value="xml"/>
 *     &lt;enumeration value="xls"/>
 *     &lt;enumeration value="ooxml"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EexportAs")
@XmlEnum
public enum EexportAs {

    @XmlEnumValue("csv")
    CSV("csv"),
    @XmlEnumValue("json")
    JSON("json"),
    @XmlEnumValue("xml")
    XML("xml"),
    @XmlEnumValue("xls")
    XLS("xls"),
    @XmlEnumValue("ooxml")
    OOXML("ooxml");
    private final String value;

    EexportAs(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EexportAs fromValue(String v) {
        for (EexportAs c: EexportAs.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
