//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 10:21:58 下午 CST 
//


package com.solmix.api.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.solmix.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Module_QNAME = new QName("http://www.solmix.com/xmlns/datasource/v1.0.1", "module");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.solmix.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ToperationBindings }
     * 
     */
    public ToperationBindings createToperationBindings() {
        return new ToperationBindings();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link Tvalue }
     * 
     */
    public Tvalue createTvalue() {
        return new Tvalue();
    }

    /**
     * Create an instance of {@link Tobject }
     * 
     */
    public Tobject createTobject() {
        return new Tobject();
    }

    /**
     * Create an instance of {@link TvalueMap }
     * 
     */
    public TvalueMap createTvalueMap() {
        return new TvalueMap();
    }

    /**
     * Create an instance of {@link TsqlPara }
     * 
     */
    public TsqlPara createTsqlPara() {
        return new TsqlPara();
    }

    /**
     * Create an instance of {@link Tdescription }
     * 
     */
    public Tdescription createTdescription() {
        return new Tdescription();
    }

    /**
     * Create an instance of {@link Tsecurity }
     * 
     */
    public Tsecurity createTsecurity() {
        return new Tsecurity();
    }

    /**
     * Create an instance of {@link Tvalidator }
     * 
     */
    public Tvalidator createTvalidator() {
        return new Tvalidator();
    }

    /**
     * Create an instance of {@link TdataSource }
     * 
     */
    public TdataSource createTdataSource() {
        return new TdataSource();
    }

    /**
     * Create an instance of {@link Tfields }
     * 
     */
    public Tfields createTfields() {
        return new Tfields();
    }

    /**
     * Create an instance of {@link TqueryClauses }
     * 
     */
    public TqueryClauses createTqueryClauses() {
        return new TqueryClauses();
    }

    /**
     * Create an instance of {@link ToperationBinding }
     * 
     */
    public ToperationBinding createToperationBinding() {
        return new ToperationBinding();
    }

    /**
     * Create an instance of {@link TfieldNameValue }
     * 
     */
    public TfieldNameValue createTfieldNameValue() {
        return new TfieldNameValue();
    }

    /**
     * Create an instance of {@link Tvalidators }
     * 
     */
    public Tvalidators createTvalidators() {
        return new Tvalidators();
    }

    /**
     * Create an instance of {@link Tservice }
     * 
     */
    public Tservice createTservice() {
        return new Tservice();
    }

    /**
     * Create an instance of {@link Texport }
     * 
     */
    public Texport createTexport() {
        return new Texport();
    }

    /**
     * Create an instance of {@link Tfield }
     * 
     */
    public Tfield createTfield() {
        return new Tfield();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Module }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.solmix.com/xmlns/datasource/v1.0.1", name = "module")
    public JAXBElement<Module> createModule(Module value) {
        return new JAXBElement<Module>(_Module_QNAME, Module.class, null, value);
    }

}
