//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.28 at 12:07:19 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.solmix.com/xmlns/datasource/v1.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.solmix.api.jaxb;
