//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 10:21:58 下午 CST 
//


package com.solmix.api.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ToperationBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ToperationBinding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Gc_client_i"/>
 *         &lt;element name="export" type="{http://www.solmix.com/xmlns/datasource/v1.0.1}Texport" minOccurs="0"/>
 *         &lt;element name="queryClauses" type="{http://www.solmix.com/xmlns/datasource/v1.0.1}TqueryClauses" minOccurs="0"/>
 *         &lt;group ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Gs_with_operation"/>
 *         &lt;element name="outputs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;group ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Gs_operation"/>
 *         &lt;group ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Gs_extention"/>
 *         &lt;element name="command" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;group ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Gs_customFields"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Ac_client_i"/>
 *       &lt;attGroup ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Atransaction"/>
 *       &lt;attGroup ref="{http://www.solmix.com/xmlns/datasource/v1.0.1}Ac_action"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ToperationBinding", propOrder = {
    "callbackParam",
    "testData",
    "export",
    "queryClauses",
    "service",
    "security",
    "outputs",
    "criteria",
    "values",
    "cache",
    "configuration",
    "command",
    "customCriteriaFields",
    "customValueFields",
    "excludeCriteriaFields",
    "customFields"
})
public class ToperationBinding {

    protected String callbackParam;
    protected Tobject testData;
    protected Texport export;
    protected TqueryClauses queryClauses;
    protected Tservice service;
    protected Tsecurity security;
    protected String outputs;
    protected List<TfieldNameValue> criteria;
    protected List<TfieldNameValue> values;
    protected Tobject cache;
    protected Tobject configuration;
    protected String command;
    protected String customCriteriaFields;
    protected String customValueFields;
    protected String excludeCriteriaFields;
    protected String customFields;
    @XmlAttribute
    protected EdataProtocol dataProtocol;
    @XmlAttribute
    protected String dataURL;
    @XmlAttribute
    protected String dropUnknownCriteria;
    @XmlAttribute
    protected Boolean dropExtraFields;
    @XmlAttribute
    protected ErequestTransport dataTransport;
    @XmlAttribute
    protected String recordXPath;
    @XmlAttribute
    protected String tagName;
    @XmlAttribute
    protected Boolean useHttpProxy;
    @XmlAttribute
    protected EdataFormat dataFormat;
    @XmlAttribute
    protected String testFileName;
    @XmlAttribute
    protected Boolean autoJoinTransactions;
    @XmlAttribute
    protected Boolean allowMultiUpdate;
    @XmlAttribute(required = true)
    protected Eoperation operationType;
    @XmlAttribute
    protected String operationId;
    @XmlAttribute
    protected Boolean preventHTTPCaching;
    @XmlAttribute
    protected String serverMethod;

    /**
     * Gets the value of the callbackParam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallbackParam() {
        return callbackParam;
    }

    /**
     * Sets the value of the callbackParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallbackParam(String value) {
        this.callbackParam = value;
    }

    /**
     * Gets the value of the testData property.
     * 
     * @return
     *     possible object is
     *     {@link Tobject }
     *     
     */
    public Tobject getTestData() {
        return testData;
    }

    /**
     * Sets the value of the testData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tobject }
     *     
     */
    public void setTestData(Tobject value) {
        this.testData = value;
    }

    /**
     * Gets the value of the export property.
     * 
     * @return
     *     possible object is
     *     {@link Texport }
     *     
     */
    public Texport getExport() {
        return export;
    }

    /**
     * Sets the value of the export property.
     * 
     * @param value
     *     allowed object is
     *     {@link Texport }
     *     
     */
    public void setExport(Texport value) {
        this.export = value;
    }

    /**
     * Gets the value of the queryClauses property.
     * 
     * @return
     *     possible object is
     *     {@link TqueryClauses }
     *     
     */
    public TqueryClauses getQueryClauses() {
        return queryClauses;
    }

    /**
     * Sets the value of the queryClauses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TqueryClauses }
     *     
     */
    public void setQueryClauses(TqueryClauses value) {
        this.queryClauses = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link Tservice }
     *     
     */
    public Tservice getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tservice }
     *     
     */
    public void setService(Tservice value) {
        this.service = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Tsecurity }
     *     
     */
    public Tsecurity getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tsecurity }
     *     
     */
    public void setSecurity(Tsecurity value) {
        this.security = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputs(String value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TfieldNameValue }
     * 
     * 
     */
    public List<TfieldNameValue> getCriteria() {
        if (criteria == null) {
            criteria = new ArrayList<TfieldNameValue>();
        }
        return this.criteria;
    }

    /**
     * Gets the value of the values property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the values property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TfieldNameValue }
     * 
     * 
     */
    public List<TfieldNameValue> getValues() {
        if (values == null) {
            values = new ArrayList<TfieldNameValue>();
        }
        return this.values;
    }

    /**
     * Gets the value of the cache property.
     * 
     * @return
     *     possible object is
     *     {@link Tobject }
     *     
     */
    public Tobject getCache() {
        return cache;
    }

    /**
     * Sets the value of the cache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tobject }
     *     
     */
    public void setCache(Tobject value) {
        this.cache = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Tobject }
     *     
     */
    public Tobject getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tobject }
     *     
     */
    public void setConfiguration(Tobject value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the customCriteriaFields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomCriteriaFields() {
        return customCriteriaFields;
    }

    /**
     * Sets the value of the customCriteriaFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomCriteriaFields(String value) {
        this.customCriteriaFields = value;
    }

    /**
     * Gets the value of the customValueFields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomValueFields() {
        return customValueFields;
    }

    /**
     * Sets the value of the customValueFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomValueFields(String value) {
        this.customValueFields = value;
    }

    /**
     * Gets the value of the excludeCriteriaFields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludeCriteriaFields() {
        return excludeCriteriaFields;
    }

    /**
     * Sets the value of the excludeCriteriaFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludeCriteriaFields(String value) {
        this.excludeCriteriaFields = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomFields() {
        return customFields;
    }

    /**
     * Sets the value of the customFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomFields(String value) {
        this.customFields = value;
    }

    /**
     * Gets the value of the dataProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link EdataProtocol }
     *     
     */
    public EdataProtocol getDataProtocol() {
        return dataProtocol;
    }

    /**
     * Sets the value of the dataProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdataProtocol }
     *     
     */
    public void setDataProtocol(EdataProtocol value) {
        this.dataProtocol = value;
    }

    /**
     * Gets the value of the dataURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataURL() {
        return dataURL;
    }

    /**
     * Sets the value of the dataURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataURL(String value) {
        this.dataURL = value;
    }

    /**
     * Gets the value of the dropUnknownCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropUnknownCriteria() {
        return dropUnknownCriteria;
    }

    /**
     * Sets the value of the dropUnknownCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropUnknownCriteria(String value) {
        this.dropUnknownCriteria = value;
    }

    /**
     * Gets the value of the dropExtraFields property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDropExtraFields() {
        return dropExtraFields;
    }

    /**
     * Sets the value of the dropExtraFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDropExtraFields(Boolean value) {
        this.dropExtraFields = value;
    }

    /**
     * Gets the value of the dataTransport property.
     * 
     * @return
     *     possible object is
     *     {@link ErequestTransport }
     *     
     */
    public ErequestTransport getDataTransport() {
        return dataTransport;
    }

    /**
     * Sets the value of the dataTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErequestTransport }
     *     
     */
    public void setDataTransport(ErequestTransport value) {
        this.dataTransport = value;
    }

    /**
     * Gets the value of the recordXPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordXPath() {
        return recordXPath;
    }

    /**
     * Sets the value of the recordXPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordXPath(String value) {
        this.recordXPath = value;
    }

    /**
     * Gets the value of the tagName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * Sets the value of the tagName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagName(String value) {
        this.tagName = value;
    }

    /**
     * Gets the value of the useHttpProxy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseHttpProxy() {
        return useHttpProxy;
    }

    /**
     * Sets the value of the useHttpProxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseHttpProxy(Boolean value) {
        this.useHttpProxy = value;
    }

    /**
     * Gets the value of the dataFormat property.
     * 
     * @return
     *     possible object is
     *     {@link EdataFormat }
     *     
     */
    public EdataFormat getDataFormat() {
        return dataFormat;
    }

    /**
     * Sets the value of the dataFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdataFormat }
     *     
     */
    public void setDataFormat(EdataFormat value) {
        this.dataFormat = value;
    }

    /**
     * Gets the value of the testFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestFileName() {
        return testFileName;
    }

    /**
     * Sets the value of the testFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestFileName(String value) {
        this.testFileName = value;
    }

    /**
     * Gets the value of the autoJoinTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoJoinTransactions() {
        return autoJoinTransactions;
    }

    /**
     * Sets the value of the autoJoinTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoJoinTransactions(Boolean value) {
        this.autoJoinTransactions = value;
    }

    /**
     * Gets the value of the allowMultiUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowMultiUpdate() {
        return allowMultiUpdate;
    }

    /**
     * Sets the value of the allowMultiUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowMultiUpdate(Boolean value) {
        this.allowMultiUpdate = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link Eoperation }
     *     
     */
    public Eoperation getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eoperation }
     *     
     */
    public void setOperationType(Eoperation value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the operationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationId() {
        return operationId;
    }

    /**
     * Sets the value of the operationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationId(String value) {
        this.operationId = value;
    }

    /**
     * Gets the value of the preventHTTPCaching property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreventHTTPCaching() {
        return preventHTTPCaching;
    }

    /**
     * Sets the value of the preventHTTPCaching property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreventHTTPCaching(Boolean value) {
        this.preventHTTPCaching = value;
    }

    /**
     * Gets the value of the serverMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerMethod() {
        return serverMethod;
    }

    /**
     * Sets the value of the serverMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerMethod(String value) {
        this.serverMethod = value;
    }

}
