//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.13 at 12:58:28 上午 CST 
//

package org.solmix.api.jaxb.request;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for Roperation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Roperation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="appID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="componentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operationConfig" type="{http://www.solmix.com/xmlns/requestdata/v1.0.1}RoperationConfig"/>
 *         &lt;element name="outputs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;group ref="{http://www.solmix.com/xmlns/requestdata/v1.0.1}G_grid"/>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;group ref="{http://www.solmix.com/xmlns/requestdata/v1.0.1}Gexport"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Roperation", propOrder = { "appID", "componentId", "dataSource", "operationType", "operationId", "repo", "operationConfig",
    "outputs", "startRow", "endRow", "sortBy", "criteria", "values", "oldValues", "textMatchStyle", "requestId", "exportResults", "exportAs",
    "exportFilename", "lineBreakStyle", "exportDelimiter", "exportTitleSeparatorChar", "exportDisplay", "exportHeader", "exportFooter",
    "exportFields" })
public class Roperation
{

    @XmlElement(required = true)
    protected String appID;

    protected String componentId;

    // @XmlElement(required = true)
    protected Object operationId;

    protected String outputs;

    protected int startRow;

    protected int endRow;

    protected List<String> sortBy;

    protected Map<String, Object> criteria;

    protected Map<String, Object> values;

    protected Map<String, Object> oldValues;

    protected String textMatchStyle;

    @XmlElement(required = true)
    protected String requestId;

    protected boolean exportResults;

    @XmlElement(required = true)
    protected String exportAs;

    @XmlElement(required = true)
    protected String exportFilename;

    @XmlElement(required = true)
    protected String lineBreakStyle;

    @XmlElement(required = true)
    protected String exportDelimiter;

    @XmlElement(required = true)
    protected String exportTitleSeparatorChar;

    @XmlElement(required = true)
    protected Boolean exportDatesAsFormattedString;

    @XmlElement(required = true)
    protected String exportDisplay;

    @XmlElement(required = true)
    protected String exportHeader;

    @XmlElement(required = true)
    protected String exportFooter;

    @XmlElement(required = true)
    protected String exportFields;

    @XmlElement(required = true)
    protected String dataSource;

    @XmlElement(required = true)
    protected String operationType;

    protected String repo;

    /**
     * Gets the value of the appID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAppID() {
        return appID;
    }

    /**
     * Sets the value of the appID property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAppID(String value) {
        this.appID = value;
    }

    /**
     * Gets the value of the componentId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getComponentId() {
        return componentId;
    }

    /**
     * Sets the value of the componentId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setComponentId(String value) {
        this.componentId = value;
    }

    /**
     * @return the operationId
     */
    public Object getOperationId() {
        return operationId;
    }

    /**
     * @param operationId the operationId to set
     */
    public void setOperationId(Object operationId) {
        this.operationId = operationId;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOutputs(String value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the startRow property.
     * 
     */
    public int getStartRow() {
        return startRow;
    }

    /**
     * Sets the value of the startRow property.
     * 
     */
    public void setStartRow(int value) {
        this.startRow = value;
    }

    /**
     * Gets the value of the endRow property.
     * 
     */
    public int getEndRow() {
        return endRow;
    }

    /**
     * Sets the value of the endRow property.
     * 
     */
    public void setEndRow(int value) {
        this.endRow = value;
    }

    /**
     * Gets the value of the sortBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the sortBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSortBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getSortBy() {
        if (sortBy == null) {
            sortBy = new ArrayList<String>();
        }
        return this.sortBy;
    }

    /**
     * @param sortBy the sortBy to set
     */
    public void setSortBy(List<String> sortBy) {
        this.sortBy = sortBy;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return possible object is {@link Map<String,String> }
     * 
     */
    @XmlJavaTypeAdapter(MapAdapter.class)
    public Map<String, Object> getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value allowed object is {@link Map<String,String> }
     * 
     */
    public void setCriteria(Map<String, Object> value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return possible object is {@link Map<String,String> }
     * 
     */
    @XmlJavaTypeAdapter(MapAdapter.class)
    public Map<String, Object> getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value allowed object is {@link Map<String,String> }
     * 
     */
    public void setValues(Map<String, Object> value) {
        this.values = value;
    }

    /**
     * Gets the value of the oldValues property.
     * 
     * @return possible object is {@link Map<String,String> }
     * 
     */
    @XmlJavaTypeAdapter(MapAdapter.class)
    public Map<String, Object> getOldValues() {
        return oldValues;
    }

    /**
     * Sets the value of the oldValues property.
     * 
     * @param value allowed object is {@link Map<String,String> }
     * 
     */
    public void setOldValues(Map<String, Object> value) {
        this.oldValues = value;
    }

    /**
     * Gets the value of the textMatchStyle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTextMatchStyle() {
        return textMatchStyle;
    }

    /**
     * Sets the value of the textMatchStyle property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTextMatchStyle(String value) {
        this.textMatchStyle = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the exportResults property.
     * 
     */
    public boolean isExportResults() {
        return exportResults;
    }

    /**
     * Sets the value of the exportResults property.
     * 
     */
    public void setExportResults(boolean value) {
        this.exportResults = value;
    }

    /**
     * Gets the value of the exportAs property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportAs() {
        return exportAs;
    }

    /**
     * Sets the value of the exportAs property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportAs(String value) {
        this.exportAs = value;
    }

    /**
     * Gets the value of the exportFilename property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportFilename() {
        return exportFilename;
    }

    /**
     * Sets the value of the exportFilename property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportFilename(String value) {
        this.exportFilename = value;
    }

    /**
     * Gets the value of the lineBreakStyle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLineBreakStyle() {
        return lineBreakStyle;
    }

    /**
     * Sets the value of the lineBreakStyle property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLineBreakStyle(String value) {
        this.lineBreakStyle = value;
    }

    /**
     * Gets the value of the exportDelimiter property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportDelimiter() {
        return exportDelimiter;
    }

    /**
     * Sets the value of the exportDelimiter property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportDelimiter(String value) {
        this.exportDelimiter = value;
    }

    /**
     * Gets the value of the exportTitleSeparatorChar property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportTitleSeparatorChar() {
        return exportTitleSeparatorChar;
    }

    /**
     * Sets the value of the exportTitleSeparatorChar property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportTitleSeparatorChar(String value) {
        this.exportTitleSeparatorChar = value;
    }

    /**
     * Gets the value of the exportDisplay property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportDisplay() {
        return exportDisplay;
    }

    /**
     * Sets the value of the exportDisplay property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportDisplay(String value) {
        this.exportDisplay = value;
    }

    /**
     * Gets the value of the exportHeader property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportHeader() {
        return exportHeader;
    }

    /**
     * Sets the value of the exportHeader property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportHeader(String value) {
        this.exportHeader = value;
    }

    /**
     * Gets the value of the exportFooter property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportFooter() {
        return exportFooter;
    }

    /**
     * Sets the value of the exportFooter property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportFooter(String value) {
        this.exportFooter = value;
    }

    /**
     * Gets the value of the exportFields property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExportFields() {
        return exportFields;
    }

    /**
     * Sets the value of the exportFields property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExportFields(String value) {
        this.exportFields = value;
    }

    /**
     * @return the dataSource
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * @param dataSource the dataSource to set
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * @return the operationType
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * @param operationType the operationType to set
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * @return the repo
     */
    public String getRepo() {
        return repo;
    }

    /**
     * @param repo the repo to set
     */
    public void setRepo(String repo) {
        this.repo = repo;
    }

    public Boolean getExportDatesAsFormattedString() {
        return exportDatesAsFormattedString;
    }

    public void setExportDatesAsFormattedString(Boolean exportDatesAsFormattedString) {
        this.exportDatesAsFormattedString = exportDatesAsFormattedString;
    }

}
