//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 04:57:48 下午 CST 
//


package org.solmix.api.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Eoperation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Eoperation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fetch"/>
 *     &lt;enumeration value="add"/>
 *     &lt;enumeration value="update"/>
 *     &lt;enumeration value="remove"/>
 *     &lt;enumeration value="validate"/>
 *     &lt;enumeration value="custom"/>
 *     &lt;enumeration value="replace"/>
 *     &lt;enumeration value="downloadFile"/>
 *     &lt;enumeration value="viewFile"/>
 *     &lt;enumeration value="loadSchema"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Eoperation")
@XmlEnum
public enum Eoperation {

    @XmlEnumValue("fetch")
    FETCH("fetch"),
    @XmlEnumValue("add")
    ADD("add"),
    @XmlEnumValue("update")
    UPDATE("update"),
    @XmlEnumValue("remove")
    REMOVE("remove"),
    @XmlEnumValue("validate")
    VALIDATE("validate"),
    @XmlEnumValue("custom")
    CUSTOM("custom"),
    @XmlEnumValue("replace")
    REPLACE("replace"),
    @XmlEnumValue("downloadFile")
    DOWNLOAD_FILE("downloadFile"),
    @XmlEnumValue("viewFile")
    VIEW_FILE("viewFile"),
    @XmlEnumValue("loadSchema")
    LOAD_SCHEMA("loadSchema");
    private final String value;

    Eoperation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Eoperation fromValue(String v) {
        for (Eoperation c: Eoperation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
