//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 04:57:48 下午 CST 
//


package org.solmix.api.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErequestTransport.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ErequestTransport">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="xmlHttpRequest"/>
 *     &lt;enumeration value="scriptInclude"/>
 *     &lt;enumeration value="hiddenFrame"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ErequestTransport")
@XmlEnum
public enum ErequestTransport {

    @XmlEnumValue("xmlHttpRequest")
    XML_HTTP_REQUEST("xmlHttpRequest"),
    @XmlEnumValue("scriptInclude")
    SCRIPT_INCLUDE("scriptInclude"),
    @XmlEnumValue("hiddenFrame")
    HIDDEN_FRAME("hiddenFrame");
    private final String value;

    ErequestTransport(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErequestTransport fromValue(String v) {
        for (ErequestTransport c: ErequestTransport.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
