//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.29 at 03:33:15 下午 CST 
//


package org.solmix.api.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EserverType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EserverType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="basic"/>
 *     &lt;enumeration value="sql"/>
 *     &lt;enumeration value="custom"/>
 *     &lt;enumeration value="jpa"/>
 *     &lt;enumeration value="filesystem"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EserverType")
@XmlEnum
public enum EserverType {

    @XmlEnumValue("basic")
    BASIC("basic"),
    @XmlEnumValue("sql")
    SQL("sql"),
    @XmlEnumValue("custom")
    CUSTOM("custom"),
    @XmlEnumValue("jpa")
    JPA("jpa"),
    @XmlEnumValue("filesystem")
    FILESYSTEM("filesystem");
    private final String value;

    EserverType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EserverType fromValue(String v) {
        for (EserverType c: EserverType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
